import { notFound } from "next/navigation"
import { supabasePublic } from "@/lib/supabase"
import type { AuditResult } from "@/lib/types"
import { HeroSection } from "@/components/AuditResults/HeroSection"
import { AnalyticsGrid } from "@/components/AuditResults/AnalyticsGrid"
import { ToolInsightsSection } from "@/components/AuditResults/ToolInsightsSection"

import { MethodologySection } from "@/components/AuditResults/MethodologySection"
import { ResultsNavbar } from "@/components/AuditResults/ResultsNavbar"

async function getAudit(id: string) {
  const { data, error } = await supabasePublic
    .from("audits")
    .select("*")
    .eq("id", id)
    .single()

  if (error || !data) return null

  // Map Supabase snake_case columns to TypeScript camelCase properties
  return {
    id: data.id,
    input: data.input,
    results: data.results,
    totalMonthlySavings: data.total_monthly_savings,
    totalAnnualSavings: data.total_annual_savings,
    aiSummary: data.ai_summary,
    isOptimal: data.is_optimal,
    showCredex: data.show_credex,
    createdAt: data.created_at,
    summary: data.summary,
    efficiencyScore: data.efficiency_score,
    referralCode: data.referral_code,
  } as AuditResult
}

export async function generateMetadata({ params }: { params: { id: string } }) {
  const audit = await getAudit(params.id)
  if (!audit) return { title: "Audit Not Found — Vantage" }

  const savings = audit.totalMonthlySavings
  const title = savings > 0
    ? `Potential savings of $${savings.toFixed(0)}/mo found`
    : "AI spend is optimized"

  return {
    title: `${title} — Vantage`,
    description: "Executive AI spend audit report generated by Vantage.",
  }
}

export default async function AuditResultsPage({ params }: { params: { id: string } }) {
  const audit = await getAudit(params.id)

  if (!audit) {
    notFound()
  }

  const totalSpend = audit.input.tools.reduce((acc, t) => acc + Math.max(0, t.monthlySpend), 0)

  return (
    <div className="min-h-screen bg-white">
      <ResultsNavbar />

      <main className="mx-auto w-[95%] max-w-screen-2xl px-2 sm:px-6 pt-32 pb-24">
        {/* PDF Only Header */}
        <div className="hidden print:flex items-center justify-between mb-12 border-b border-black/5 pb-6">
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 bg-[#111] rounded-xl flex items-center justify-center text-white font-bold">V</div>
            <div>
              <span className="text-xl font-medium tracking-tight text-[#111] block">Vantage</span>
              <span className="text-[10px] font-bold uppercase tracking-widest text-[#666]">AI Spend Audit</span>
            </div>
          </div>
          <div className="text-right">
            <p className="text-[10px] font-bold uppercase tracking-widest text-[#9CA3AF] mb-1">Generated On</p>
            <p className="text-sm font-medium text-[#111]">{new Date(audit.createdAt).toLocaleDateString()}</p>
          </div>
        </div>

        <HeroSection audit={audit} totalSpend={totalSpend} />

        <AnalyticsGrid audit={audit} totalSpend={totalSpend} />

        <ToolInsightsSection audit={audit} />

        <div className="space-y-12">
          <MethodologySection audit={audit} />
        </div>


      </main>
    </div>
  )
}
